scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'exporter'
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets: ['app:5000']